### ISSUE TITLE
Integrate segment.io

### ISSUE THREAD

**Issue by ffffranklin** [ffffranklin/jester#9]
**Tasks**
 - [x] Develop tracking plann
 - [x] Set up an account
 - [x] Set up a error tracker
 - [x] Set up a segment.io project for jester

**Notes**

 * Would be cool if it tracked how long we listen to stations 
  * might need a service that we poll to track when we are listening
  * after it stops polling that service could send the event to segment.io
